/* no sentinel defines ... on purpose */

// GTPSA_FUNC_ARG1( abs    )
GTPSA_FUNC_ARG1( sqrt   )
GTPSA_FUNC_ARG1( exp	)
GTPSA_FUNC_ARG1( log	)
GTPSA_FUNC_ARG1( sin	)
GTPSA_FUNC_ARG1( cos	)
GTPSA_FUNC_ARG1( tan	)
GTPSA_FUNC_ARG1( cot	)
GTPSA_FUNC_ARG1( sinc	)
GTPSA_FUNC_ARG1( sinh	)
GTPSA_FUNC_ARG1( cosh	)
GTPSA_FUNC_ARG1( tanh	)
GTPSA_FUNC_ARG1( coth	)
GTPSA_FUNC_ARG1( sinhc  )
GTPSA_FUNC_ARG1( asin	)
GTPSA_FUNC_ARG1( acos	)
GTPSA_FUNC_ARG1( atan	)
GTPSA_FUNC_ARG1( acot	)
GTPSA_FUNC_ARG1( asinc  )
GTPSA_FUNC_ARG1( asinh  )
GTPSA_FUNC_ARG1( acosh  )
GTPSA_FUNC_ARG1( atanh  )
GTPSA_FUNC_ARG1( acoth  )
GTPSA_FUNC_ARG1( asinhc )
GTPSA_FUNC_ARG1( erf	)
GTPSA_FUNC_ARG1( erfc   )
