/* no sentinel defines ... on purpose */

FUNC_ARG1( abs    )
FUNC_ARG1( sqrt   )
FUNC_ARG1( exp	  )
FUNC_ARG1( log	  )
FUNC_ARG1( sin	  )
FUNC_ARG1( cos	  )
FUNC_ARG1( tan	  )
FUNC_ARG1( cot	  )
FUNC_ARG1( sinc	  )
FUNC_ARG1( sinh	  )
FUNC_ARG1( cosh	  )
FUNC_ARG1( tanh	  )
FUNC_ARG1( coth	  )
FUNC_ARG1( sinhc  )
FUNC_ARG1( asin	  )
FUNC_ARG1( acos	  )
FUNC_ARG1( atan	  )
FUNC_ARG1( acot	  )
FUNC_ARG1( asinc  )
FUNC_ARG1( asinh  )
FUNC_ARG1( acosh  )
FUNC_ARG1( atanh  )
FUNC_ARG1( acoth  )
FUNC_ARG1( asinhc )
FUNC_ARG1( erf	  )
FUNC_ARG1( erfc   )
