name: build orchestration

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # cmake is used to install file ... defaults to /usr/local
  LD_LIBRARY_PATH: /usr/local/lib

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-deb-package:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    runs-on: ubuntu-latest

    steps:
      - name: checkout gtpsa-cpp code
        uses: actions/checkout@v4
        with:
          submodules: True

      - name: ubuntu-deb-package
        uses: ./.github/workflows/composite-action/ubuntu-deb-package

  python-package:
    needs : ubuntu-deb-package
    runs-on: ubuntu-latest

    steps:
      - name: checkout gtpsa-cpp code
        uses: actions/checkout@v4
        with:
           submodules: False

      - name: python-build
        uses: ./.github/workflows/composite-action/python-build

  pypi-publish:
