name: python-package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
jobs:

  python-package:
    name : gtpsa build and install python package
    needs : ubuntu-deb-package
    runs-on: ubuntu-latest

    steps:
    - name: checkout gtpsa-cpp code
      uses: actions/checkout@v4

    - name: Downloads artefact
      uses: actions/download-artifact@v4
      with:
        name: gtpsa-release-deb
    - name: setup environment
      run: |
        sudo apt update
        sudo apt install python3-dev python3-venv libarmadillo-dev ./gtpsa*.deb

    - name: setup python
      run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip wheel build pytest 'numpy>2.0' pandas
          find /usr -name 'libgtpsa*'
          find . -type d
          gtpsa_PREFIX=/usr/local python3 -m pip install -v ./python/

          python3 -m pytest ./python/tests
