name: python-package

runs:
  using: "composite"

    steps:
    - name: checkout gtpsa code
      uses: actions/checkout@v4

#    - name: Downloads artefact
#      uses: actions/download-artifact@v4
#      with:
#        name: gtpsa-release-deb
#    - name: setup environment
#      run: |
#        sudo apt update
#        sudo apt install python3-dev python3-venv libarmadillo-dev ./gtpsa*.deb
#
#    - name: setup python
#      run: |
#          python3 -m venv venv
#          . venv/bin/activate
#          python3 -m pip install --upgrade pip wheel build pytest 'numpy>2.0' pandas
#          find /usr -name 'libgtpsa*'
#          find . -type d
#          gtpsa_PREFIX=/usr/local python3 -m pip install -v ./python/
#
#          python3 -m pytest ./python/tests
